services:
  - type: web
    name: dailyrecord
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn dailyrecord.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: dailyrecord.settings
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: dailyrecord_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: dailyrecord-redis
          property: connectionString

  - type: redis
    name: dailyrecord-redis
    ipAllowList: []
    plan: free

databases:
  - name: dailyrecord_db
    plan: free 